Repository diffgram/diffgram, pull requests merged in 2021-09, with the labels that each got.

#267 Parallel Cypress Tests
  .github/workflows/diffgram_testing.yaml
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_data_integrity.js
Labels: feature, testing

#274 Remove related tasks when archiving / retrying input
  walrus/methods/input/input_update.py
Labels: ready_to_merge, bugfix

#271 Preview Image Parallel Regen For Sequences
  default/methods/annotation/annotation.py
  default/methods/video/sequence_preview_create.py
  default/routes_init.py
  default/tests/methods/video/test_sequence_preview_create.py
  default/tests/shared/test_annotation.py
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/video/sequence_list.vue
  frontend/src/components/vue_canvas/instance_list.vue
  shared/annotation.py
  shared/database/video/sequence.py
  shared/tests/test_utils/data_mocking.py
Labels: ready_to_merge, feature

#285 Polygon Figures Merge
  default/tests/shared/test_annotation.py
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/context_menu/context_menu.vue
  frontend/src/components/vue_canvas/instance_list.vue
  frontend/src/store.js
  shared/annotation.py
  shared/database/system_events/system_events.py
Labels: ready_to_merge, feature

#243 Cross File Copy Paste
  frontend/cypress/integration/diffgram/user/user_login_spec.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/store.js
Labels: enhancement, pending_work

#296 Add figure id to polygon when adding midpoint
  frontend/src/components/annotation/annotation_core.vue
Labels: ready_to_merge, bugfix

#294 Improve Performance of Report Queries
  default/methods/report/report_runner.py
  shared/alembic/versions_opencore/alembic_2021_09_16_11_27_c1e5966dc826_add_index_for_instance_table.py
Labels: pending_work, performance

#299 fix: handle Forbidden exceptions correctly
  default/main.py
  shared/error_handlers/error_handlers.py
  walrus/main.py
Labels: ready_to_merge, bugfix

#300 Small add more descriptive permissions failure messages
  shared/permissions/project_permissions.py
Labels: ready_to_merge

#301 improved comments and documentation for data_tools classes
  shared/data_tools_core.py
  shared/data_tools_core_azure.py
  shared/data_tools_core_gcp.py
  shared/data_tools_core_s3.py
Labels: ready_to_merge, feature

#307 fix: duplicate file search query
  walrus/methods/input/process_media.py
Labels: ready_to_merge, bugfix
