Repository diffgram/diffgram, pull requests merged in 2021-11, with the labels that each got.

#385 QA automated slideshow
  frontend/cypress/integration/diffgram/qa_slideshow/qa_slideshow_spec.js
  frontend/index.html
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/annotation/instance_diff_dialog.vue
  frontend/src/components/annotation/qa_carousel.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/annotation/userscript/userscript.ts
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/tests/unit/annotation/annotation_core.spec.js
  frontend/tests/unit/annotation/qa_carousel.spec.js
  frontend/tests/unit/annotation/toolbar.spec.js
Labels: work-in-progress

#404 Mock Task For UI Schema Creation
  frontend/cypress/integration/diffgram/annotate_files/03_instance_template_annotation_spec.js
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/source_control/file_manager_sheet.vue
  frontend/src/components/ui_schema/ui_schema_task_mock.js
  frontend/yarn.lock
Labels: ready_to_merge, feature

#407 Add status to task report
  default/methods/report/report_runner.py
  frontend/src/components/report/report.vue
Labels: ready_to_merge, feature

#401 Add mailgun variables request
  default/methods/configs/mailgun_is_set.py
  default/routes_init.py
  docker-compose.yaml
  frontend/config/prod.env.js
  frontend/cypress/support/commands.js
  frontend/src/components/user/login.vue
  frontend/src/services/configService.js
  frontend/tests/unit/user/login.spec.js
  install.py
  shared/settings/settings.py
Labels: user-experience

#426 Auto Assign Reviewer on Task Completion
  default/methods/annotation/annotation.py
  default/methods/task/task/task_review.py
  default/methods/task/task/task_update.py
  default/methods/task/task_template/job_new_or_update.py
  default/tests/methods/task/task_template/test_job_new_or_update.py
  default/tests/shared/database/task/test_task_user.py
  default/tests/shared/utils/task/test_task_assign_reviewer.py
  default/tests/shared/utils/task/test_task_complete.py
  shared/database/event/event.py
  shared/database/task/job/job.py
  shared/database/task/task.py
  shared/database/task/task_user.py
  shared/permissions/project_permissions.py
  shared/regular/regular_member.py
  shared/utils/task/task_assign_reviewer.py
  shared/utils/task/task_complete.py
Labels: ready_to_merge, feature, backend

#427 Add Random Review Frequency Support [Backend]
  default/tests/shared/utils/task/test_task_complete.py
  shared/alembic/versions_opencore/alembic_2021_11_09_09_59_3c761954bd8d_add_review_chance_column_to_job_table.py
  shared/database/task/job/job.py
  shared/utils/task/task_complete.py
Labels: ready_to_merge, feature, backend

#406 Task Events
  default/methods/annotation/annotation.py
  default/methods/task/task/task_annotator_request.py
  default/methods/task/task/task_review.py
  default/methods/task/task/task_update.py
  default/methods/task/task_event/__init__.py
  default/methods/task/task_template/job_new_or_update.py
  default/routes_init.py
  default/tests/methods/task/task/test_task_annotator_request.py
  default/tests/methods/task/task/test_task_review.py
  default/tests/methods/task/task_template/test_job_new_or_update.py
  default/tests/shared/database/task/__init__.py
  default/tests/shared/database/task/job/__init__.py
  default/tests/shared/database/task/job/test_user_to_job.py
  default/tests/shared/database/task/test_task.py
  default/tests/shared/database/task/test_task_event.py
  default/tests/shared/database/task/test_task_user.py
  default/tests/shared/utils/task/test_task_assign_reviewer.py
  default/tests/shared/utils/task/test_task_complete.py
  shared/alembic/versions_opencore/alembic_2021_11_02_12_17_8d8aac82ec53_add_taskevent_table.py
  shared/alembic/versions_opencore/alembic_2021_11_04_08_39_3631b751e139_add_taskuser_table.py
  shared/alembic/versions_opencore/alembic_2021_11_05_08_31_32dbb3259c2b_add_allow_review_columns.py
  shared/alembic/versions_opencore/alembic_2021_11_08_09_39_d7a8d65bdd87_add_relation_type_to_user_to_job_table.py
  shared/alembic/versions_opencore/alembic_2021_11_09_09_59_3c761954bd8d_add_review_chance_column_to_job_table.py
  shared/annotation.py
  shared/database/annotation/instance.py
  shared/database/event/event.py
  shared/database/task/job/job.py
  shared/database/task/job/user_to_job.py
  shared/database/task/task.py
  shared/database/task/task_event.py
  shared/database/task/task_user.py
  shared/permissions/project_permissions.py
  shared/permissions/task_permissions.py
  shared/regular/regular_member.py
  shared/tests/test_utils/data_mocking.py
  shared/utils/task/task_assign_reviewer.py
  shared/utils/task/task_complete.py
  shared/utils/task/task_update_manager.py
  walrus/methods/input/process_media.py
Labels: feature, pending_work, backend

#420 Fix autoborder
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_instance_drawing_spec.js
  frontend/cypress/integration/diffgram/annotate_files/autoborder_spec.js
  frontend/cypress/integration/diffgram/annotate_files/file_information_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/context_menu/polygon_borders_context_menu.vue
  frontend/src/components/user/login.vue
Labels: bugfix

#435 Add task complete API endpoint
  default/methods/task/task/task_complete.py
  default/routes_init.py
  default/tests/methods/task/task/test_task_complete.py
  shared/annotation.py
Labels: ready_to_merge, backend

#409 Add stats element
  default/methods/task/stats/fast_stats.py
  default/routes_init.py
  frontend/cypress/integration/diffgram/task_template/tasks_detail_pagination_spec.js
  frontend/package.json
  frontend/src/components/report/charts/pieChart.js
  frontend/src/components/stats/stats_panel.vue
  frontend/src/components/task/job/job_detail.vue
  frontend/src/components/task/job/job_detail_builder.vue
  frontend/src/components/task/job/job_info_builder.vue
  frontend/src/components/task/task/task_list.vue
  frontend/src/components/user/user_icon.vue
  frontend/src/services/jobStatsServices.js
  frontend/src/services/tasksServices.js
  frontend/src/store.js
  frontend/tests/unit/stats/stats_panel.spec.js
  frontend/yarn.lock
  shared/database/task/task.py
Labels: admin experience, analytics

#439 Add reviewers step to the task wizard
  default/methods/task/task_template/job_new_or_update.py
  frontend/cypress/integration/diffgram/task_template/task_template_create_spec.js
  frontend/src/components/task/job/task_template_wizard_creation/step_reviewers_selection.vue
  frontend/src/components/task/job/task_template_wizard_creation/step_users_selection.vue
  frontend/src/components/task/job/task_template_wizard_creation/task_template_new.vue
  frontend/src/components/task/job/task_template_wizard_creation/task_template_wizard.vue
  frontend/tests/unit/task/job/task_template_wizard_creation/step_reviewers_selection.spec.js
  shared/database/task/job/job.py
Labels: ready_to_merge, frontend-ui, front-end, ux

#432 Add/Remove User from Task API Endpoints
  default/methods/task/task/task_user_add.py
  default/methods/task/task/task_user_remove.py
  default/routes_init.py
  default/tests/methods/task/task/test_task_user_add.py
  default/tests/methods/task/task/test_task_user_remove.py
  shared/database/task/task_user.py
  shared/utils/task/task_complete.py
Labels: ready_to_merge, feature, backend

#443 Task completion dialog
  default/methods/task/task_template/job_new_or_update.py
  frontend/cypress/integration/diffgram/task_template/task_submit_to_review_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/annotation/actions/is_complete.vue
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/dialogs/review_dialog.vue
  frontend/src/services/tasksServices.js
  frontend/tests/unit/annotation/actions/is_complete.spec.js
  frontend/tests/unit/dialogs/review_dialog.spec.js
  shared/database/task/job/job.py
  walrus/methods/data_mocking/generate_data.py
Labels: ready_to_merge, front-end, tasks-workflow

#449 Display new statuses on job page
  frontend/src/components/regular_concrete/task_status_icons.vue
  frontend/src/components/stats/stats_panel.vue
  frontend/tests/unit/regular_concrete/task_status_icons.spec.js
  shared/database/task/task.py
Labels: ready_to_merge, front-end, user-experience

#442 Small improvements to the main toolbar
  frontend/cypress/integration/diffgram/user/user_login_spec.js
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/project/project_new.vue
  frontend/src/services/projectServices.js
  frontend/src/store.js
  frontend/tests/unit/main_menu/menu.spec.js
Labels: ready_to_merge, frontend-ui, front-end, user-experience
