Repository diffgram/diffgram, pull requests merged in 2021-05, with the labels that each got.

#51 Add External DB To Install Script
  docker-compose.yaml
  install.py
Labels: feature, ready_to_merge

#52 fix: Labelbox API now expect string in the external ID's
  walrus/methods/connectors/labelbox_connector.py
Labels: bugfix, ready_to_merge

#58 bugfix: small fix on building url to append a slash when non-existent.
  default/methods/user/account/account_verify.py
Labels: bugfix, ready_to_merge

#62 Cypress CPU Profiling
  .github/workflows/diffgram_testing.yaml
Labels: bugfix

#46 Decouple Media Core
  .circleci/circleci_docker_images/e2e_testing/Dockerfile
  .circleci/config.yml
  default/methods/source_control/file/file_browser.py
  default/methods/task/stats/__init__.py
  default/methods/task/stats/stats_job.py
  default/methods/task/stats/stats_leaderboard.py
  default/methods/task/stats/stats_task.py
  default/methods/task/task/task_next.py
  default/routes_init.py
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_context_menu_spec.js
  frontend/src/components/annotation/actions/is_complete.vue
  frontend/src/components/annotation/annotation_assignment_review.vue
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_full.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/file_relations_card.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/annotation/labels_view.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/annotation/task_relations_card.vue
  frontend/src/components/annotation/trainer/trainer_annotation.vue
  frontend/src/components/discussions/issues_sidepanel.vue
  frontend/src/components/source_control/file_manager_sheet.vue
  frontend/src/components/task/file/file_select.vue
  frontend/src/components/task/task/task_annotation_diff.vue
  frontend/src/components/video/sequence_list.vue
  frontend/src/components/video/video.vue
  frontend/src/components/vue_canvas/current_instance.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/components/vue_canvas/instance_list.vue
  frontend/src/router/router.js
  shared/database/task/task.py
Labels: enhancement, ready_to_merge

#63 Improve UI, especially in video and task context - WIP
  .circleci/circleci_docker_images/e2e_testing/Dockerfile
  .circleci/config.yml
  default/methods/source_control/file/file_browser.py
  default/methods/task/stats/__init__.py
  default/methods/task/stats/stats_job.py
  default/methods/task/stats/stats_leaderboard.py
  default/methods/task/stats/stats_task.py
  default/methods/task/task/task_next.py
  default/routes_init.py
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_attributes_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_context_menu_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_file_information_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_instance_drawing_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_undo_redo_instances_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js
  frontend/cypress/integration/diffgram/annotate_files/annotation_files_advanced_settings_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/annotation/actions/is_complete.vue
  frontend/src/components/annotation/annotation_assignment_review.vue
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_full.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/file_relations_card.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/annotation/labels_view.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/annotation/task_relations_card.vue
  frontend/src/components/annotation/text_annotation/text_annotation_core.vue
  frontend/src/components/annotation/text_annotation/text_highlighter.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/annotation/trainer/trainer_annotation.vue
  frontend/src/components/annotation/trainer/trainer_menu.vue
  frontend/src/components/discussions/issues_sidepanel.vue
  frontend/src/components/label/label_select_annotation.vue
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/source_control/file_manager_sheet.vue
  frontend/src/components/task/file/file_select.vue
  frontend/src/components/task/task/task_annotation_diff.vue
  frontend/src/components/video/sequence_list.vue
  frontend/src/components/video/video.vue
  frontend/src/components/vue_canvas/current_instance.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/components/vue_canvas/instance_list.vue
  frontend/src/router/router.js
  local_dispatcher/local_dispatch.py
  shared/database/task/task.py
Labels: ease of use, feature, frontend-ui, pending_work

#70 bugfix: change dummy image to tianon/true
  install.py
Labels: bugfix, ready_to_merge

#77 Improve UI styles of toolbar
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/label/label_select_annotation.vue
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/regular/diffgram_select.vue
Labels: feature, ready_to_merge

#78 fix: fix alembic version ordering
  shared/alembic/versions_opencore/alembic_2021_05_12_10_11_990839b415fc_add_prelabeled_data_to_input_batch.py
Labels: bugfix

#79 Install Scripts Improvements
  README.md
  install.py
  requirements.txt
Labels: enhancement

#80 Deprecate video framerate conversion
  frontend/src/components/project/settings.vue
  walrus/methods/video/video.py
Labels: ready_to_merge, refactor

#81 Code cleanup
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_project_list.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/commands/create_instance_command.js
  frontend/src/components/annotation/instance_diff_dialog.vue
  frontend/src/components/annotation/labels_edit.vue
  frontend/src/components/annotation/labels_view.vue
  frontend/src/components/annotation/trainer/trainer_job_info.vue
  frontend/src/components/annotation/userscript/userscript.ts
  frontend/src/components/annotation/userscript/userscript.vue
  frontend/src/components/annotation/userscript/userscript_select.vue
  frontend/src/components/connection/connection_form.vue
  frontend/src/components/input/input_view.vue
  frontend/src/components/label/label_list_data_table.vue
  frontend/src/components/label/label_select_annotation.vue
  frontend/src/components/label/label_select_only.vue
  frontend/src/components/share/share_member_list.vue
  frontend/src/components/task/credential/credential_list.vue
  frontend/src/components/task/credential/credential_type_new_or_edit.vue
  frontend/src/components/task/file/dir_attach.vue
  frontend/src/components/task/file/file_attach.vue
  frontend/src/components/task/guide/guide_list.vue
  frontend/src/components/task/guide/guide_new_or_edit.vue
  frontend/src/components/task/job/job_detail.vue
  frontend/src/components/task/job/job_info_builder.vue
  frontend/src/components/task/job/job_launches_list.vue
  frontend/src/components/task/job/job_list.vue
  frontend/src/components/task/job/job_new_form.vue
  frontend/src/components/task/job/job_select.vue
  frontend/src/components/task/job/job_start.vue
  frontend/src/components/task/job/trainer_job_preview_info.vue
  frontend/src/components/task/task/task_list.vue
  frontend/src/components/user/account/resend_verify_email.vue
  frontend/src/components/user/account/user_data_platform_new.vue
  frontend/src/components/user/account/verify_email.vue
  frontend/src/components/user/edit.vue
  frontend/src/components/user/follow_list.vue
  frontend/src/components/user/login.vue
  frontend/src/components/user/one_time_pass/new_otp.vue
  frontend/src/components/user/profile_in_menu.vue
  frontend/src/components/user/user_profile_image_edit.vue
  frontend/src/components/video/frame_preview.vue
  frontend/src/components/video/sequence_list.vue
  frontend/src/components/video/video.spec.js
  frontend/src/components/video/video.vue
  shared/connection/test_connection.py
  shared/database/source_control/file_diff.py
  walrus/methods/input/process_media.py
  walrus/tests/connectors/test_scaleai_connectors.py
  walrus/tests/methods/task/task_template/test_task_template_launch_handler.py
Labels: enhancement, ready_to_merge

#82 Fix job card title styles for long text
  frontend/src/components/task/job/job_list_card_display.vue
Labels: enhancement, ready_to_merge

#83 Add member's email to the member list in the project settings
  frontend/src/components/share/share_member_list.vue
  shared/database/user.py
Labels: feature, ready_to_merge
