Repository diffgram/diffgram, pull requests merged in 2021-12, with the labels that each got.

#458 fix: paste to next frames now fetches missing instance buffers
  frontend/src/components/annotation/annotation_core.vue
Labels: ready_to_merge, bugfix

#451 Manual user assignment to the task
  default/methods/task/task/task_list.py
  default/methods/task/task/task_user_add.py
  default/methods/task/task/task_user_modify.py
  default/methods/task/task/task_user_remove.py
  default/routes_init.py
  default/tests/methods/task/task/test_task_user_add.py
  default/tests/methods/task/task/test_task_user_remove.py
  frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js
  frontend/package.json
  frontend/src/components/dialogs/add_assignee.vue
  frontend/src/components/task/task/task_list.vue
  frontend/src/components/user/member_select.vue
  frontend/src/components/user/user_icon.vue
  frontend/src/services/tasksServices.js
  frontend/tests/unit/dialogs/add_assignee.spec.js
  frontend/tests/unit/task/task/task_list.spec.js
  shared/database/task/task.py
Labels: ready_to_merge, admin experience, front-end

#460 Re Enable Eventhub
  shared/alembic/versions_opencore/alembic_2021_12_09_12_19_7505d378b3ae_add_eventhub.py
  shared/database/event/eventhub.py
  shared/database/system_events/system_events.py
  shared/regular/regular_methods.py
  shared/settings/settings.py
  walrus/main.py
  walrus/methods/eventhub/__init__.py
  walrus/methods/eventhub/eventhub_new.py
  walrus/methods/startup/system_startup_checker.py
Labels: pending_work

#459 Add task status component
  frontend/cypress/integration/diffgram/qa_slideshow/qa_slideshow_spec.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/task_status.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/tests/unit/annotation/task_status.spec.js
  frontend/tests/unit/annotation/toolbar.spec.js
Labels: frontend-ui, user-experience

#462 fix: hide sequence list while playing
  frontend/src/components/video/sequence_list.vue
Labels: enhancement, ready_to_merge, performance

#465 Add New Settings Display
  .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml
  default/methods/configs/admin_install_info.py
  frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/toolbar.vue
Labels: ready_to_merge, feature

#467 Add indexes to file table parent_id
  shared/alembic/versions_opencore/alembic_2021_12_14_14_57_efd1cf42073a_add_indexes_parent_file_id.py
Labels: ready_to_merge, feature

#477 Fix details pointed by Anthony
  frontend/src/components/annotation/actions/is_complete.vue
  frontend/src/components/annotation/task_status.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/dialogs/review_dialog.vue
  frontend/tests/unit/dialogs/review_dialog.spec.js
  shared/database/task/task.py
  shared/database/task/task_event.py
  walrus/methods/input/upload.py
Labels: bugfix

#479 Add New Type to FIle Filter List
  default/methods/source_control/file/file_browser.py
  frontend/src/components/annotation/media_core.vue
Labels: ready_to_merge, feature
