Repository diffgram/diffgram, pull requests merged in 2022-11, with the labels that each got.

#1144 Fix: Optimize Signed URL Fetch on task context
  default/methods/source_control/file/file_get_signed_url.py
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/source_control/file_manager_sheet.vue
  frontend/src/services/fileServices.ts
  shared/database/audio/audio_file.py
  shared/database/image.py
  shared/database/source_control/file.py
  shared/database/text_file.py
  shared/url_generation.py
Labels: ready_to_merge

#1148 Prevent call to fetch global attributes if there no project string id
  frontend/src/components/attribute/attribute_group_list.vue
Labels: bugfix

#1143 Add Attribute preview to the image interafce
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/base/attribute_preview.vue
  frontend/src/components/base/standard_chip.vue
Labels: front-end, annotation-experience

#1157 Fix: Param Rename on MigrationManager
  shared/project_migration/ExternalMigrationManager.py
Labels: ready_to_merge, bugfix

#1164 Feat job pagination
  default/methods/task/task_template/job_list.py
  default/tests/methods/task/task_template/test_job_list.py
  frontend/src/components/task/job/job_list.vue
Labels: user-experience

#1170 Add show ids
  frontend/src/components/attached/global_dataset_selector.vue
  frontend/src/components/concrete/dataset/dataset_selector.vue
  frontend/src/components/project/settings.vue
Labels: frontend-ui, user-experience, user-request

#1171 Add indexes to the job table
  shared/alembic/versions_opencore/alembic_2022_11_15_12_24_f1b006dd9e9e_add_index_to_the_job_table.py
Labels: optimization

#1172 AI-49 Image Rotation
  default/methods/source_control/file/file_update_metadata.py
  default/routes_init.py
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/annotation/thumbnail.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/source_control/file_preview.vue
  frontend/src/components/vue_canvas/drawable_canvas.vue
  frontend/src/components/vue_canvas/target_reticle.vue
  frontend/src/components/vue_canvas/v_bg.vue
  frontend/src/services/fileServices.ts
  frontend/src/types/files.ts
  shared/alembic/versions_opencore/alembic_2022_11_16_09_04_25580ca9875a_new_rotation_column.py
  shared/database/image.py
  shared/export/export_generation.py
Labels: enhancement, ready_to_merge

#1173 Fix rendering on task context
  frontend/cypress/e2e/diffgram/annotate_files/10_advanced_settings.cy.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/regular/button_with_menu.vue
  frontend/src/components/vue_canvas/target_reticle.vue
Labels: bugfix

#1154 Refactor: task optimisation
  frontend/cypress/e2e/diffgram/annotate_files/07_undo_redo_instances.cy.js
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/helpers/task/TaskPrefetcher.ts
  frontend/src/services/tasksServices.js
  frontend/yarn.lock
Labels: performance, annotation-experience, task-experience

#1174 AI-35: feat: open first global attribute panel by default
  frontend/src/components/attribute/attribute_group_list.vue
  frontend/src/components/attribute/global_attributes_list.vue
Labels: ready_to_merge

#1178 Fix prefetching bug pointed on the call
  frontend/src/helpers/task/TaskPrefetcher.ts
Labels: bugfix

#1209 cleanup: removes all box creation legacy code
  frontend/src/components/annotation/annotation_core.vue
Labels: ready_to_merge, refactor

#1207 Fix: Avoid creating thumbnails Once generated
  frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js
  frontend/src/components/annotation/media_core.vue
Labels: ready_to_merge

#1210 fix: populate default value in multi select
  .github/workflows/e2e_tests.yaml
  frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js
  frontend/cypress/support/commands.js
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/attribute/attribute_group.vue
Labels: ready_to_merge, bugfix

#1220 Fix: job list API call
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/task/job/job_select.vue
  shared/helpers/sessionMaker.py
Labels: ready_to_merge, bugfix

#1222 Force updating attributes on the global instance
  frontend/src/components/annotation/annotation_core.vue
Labels: ready_to_merge, bugfix

#1224 Fix: Approval Reject Report
  default/methods/report/custom_reports/TaskReportRejectRatioReport.py
Labels: bugfix

#1229 fix: remove folder removal line
  docker-compose.yaml
Labels: bugfix

#1208 Text bug fixes
  frontend/src/components/source_control/compound_file_preview.vue
  frontend/src/components/text_annotation/render_elements/fast_label_menu.vue
  frontend/src/components/text_annotation/render_elements/selection.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/text_annotation/text_sidebar.vue
  frontend/src/components/text_annotation/text_utils/closest_token.ts
  frontend/src/components/text_annotation/text_utils/draw_rects.ts
  frontend/tests/unit/text_annotation/render_elements/fast_label_menu.spec.js
  frontend/tests/unit/text_annotation/text_annotation_core.spec.js
  frontend/tests/unit/text_annotation/text_utils/closest_token.spec.js
Labels: ready_to_merge, bugfix, text-annotation
