Repository diffgram/diffgram, pull requests merged in 2022-07, with the labels that each got.

#959 feat: Add Cognito OAuth2 Support
  default/methods/auth/oidc/oidc_auth_callback.py
  default/methods/configs/oauth2_is_set.py
  default/methods/configs/oidc_is_set.py
  default/methods/source_control/file/file_browser.py
  default/methods/startup/system_startup_checker.py
  default/methods/task/task_template/task_template_member_list.py
  default/methods/user/account/account_new.py
  default/methods/user/builder/builder_signup.py
  default/methods/user/login.py
  default/methods/user/logout.py
  default/routes_init.py
  default/tests/methods/annotation/test_instance_template_list.py
  default/tests/methods/discussions/test_discussion_update.py
  default/tests/methods/task/file/test_task_file_observers.py
  eventhandlers/startup/system_startup_checker.py
  frontend/src/components/user/login.vue
  frontend/src/components/user/login_oauth2_redirect.vue
  frontend/src/components/user/logout.vue
  frontend/src/components/user/profile_in_menu.vue
  frontend/src/router/router.js
  frontend/src/services/configService.js
  frontend/src/services/customInstance/index.js
  frontend/src/services/userServices.js
  shared/auth/CognitoDiffgramClient.py
  shared/auth/KeycloakDiffgramClient.py
  shared/auth/OAuth2Provider.py
  shared/database/notifications/notification.py
  shared/database/source_control/working_dir.py
  shared/database/task/job/job.py
  shared/database/user.py
  shared/helpers/permissions.py
  shared/permissions/general.py
  shared/query_engine/query_creator.py
  shared/settings/settings.py
  walrus/methods/startup/system_startup_checker.py
  walrus/tests/methods/export/test_export_generation.py
  walrus/tests/methods/input/test_packet.py
Labels: ready_to_merge, feature

#961 Fix Cognito Settings
  shared/settings/settings.py
Labels: ready_to_merge, bugfix

#963 Pass action output data to the next action on the action_complete
  default/methods/action/action_new.py
  default/methods/action/action_previous.py
  default/methods/action/action_update.py
  default/methods/attribute/attribute_template_group.py
  default/routes_init.py
  eventhandlers/action_runners/actions/AzureTextAnalyticsSentiment.py
  eventhandlers/action_runners/actions/DeepCheckImagePropertyOutliers.py
  eventhandlers/action_runners/actions/ExportActionRunner.py
  eventhandlers/action_runners/actions/HuggingFaceZeroShot.py
  eventhandlers/action_runners/actions/SampleActionBoilerplate.py
  eventhandlers/action_runners/actions/TaskTemplateActionRunner.py
  eventhandlers/action_runners/base/ActionRunner.py
  frontend/src/components/action/Action.ts
  frontend/src/components/action/action_configurations/create_task/create_task_action_config.vue
  frontend/src/components/action/action_configurations/create_task/task_template_config_details.vue
  frontend/src/components/action/action_configurations/hugging_face/HuggingFaceZeroShot.vue
  frontend/src/components/action/actions_config_base/pre_conditions_config.vue
  frontend/src/components/action/workflow_builder.vue
  frontend/src/services/workflowServices.js
  shared/alembic/versions_opencore/alembic_2022_07_06_19_16_bdc0a1d2c5af_added_result_to_the_event_table.py
  shared/alembic/versions_opencore/alembic_2022_07_06_20_21_2096969c6740_add_output_interface_to_the_action_tabel.py
  shared/alembic/versions_opencore/alembic_2022_07_08_10_26_a561aa77d88d_added_precondition_json_column_to_the_.py
  shared/database/action/action.py
  shared/database/action/action_template.py
  shared/database/attribute/attribute_template_group.py
  shared/database/event/event.py
Labels: actions

#971 Cognito Token Storage Size & Login Optimizations
  default/methods/auth/oidc/oidc_auth_callback.py
  default/methods/user/login.py
  default/methods/user/logout.py
  frontend/src/components/user/login.vue
  shared/helpers/permissions.py
Labels: ready_to_merge

#978 Fix multi select
  eventhandlers/action_runners/actions/HuggingFaceZeroShot.py
  frontend/src/components/text_annotation/text_annotation_core.vue
  shared/annotation.py
Labels: bugfix, text-annotation, actions

#983 Fix actions integration bug
  eventhandlers/action_runners/actions/TaskTemplateActionRunner.py
Labels: bugfix, actions

#974 Tree attribute optimisation
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/helpers/tree_view/construct_tree.ts
  shared/annotation.py
Labels: user-experience
