Repository diffgram/diffgram, pull requests merged in 2022-10, with the labels that each got.

#1081 Fix MinIO Chunking Process
  shared/data_tools_core_s3.py
  walrus/methods/input/upload.py
Labels: ready_to_merge, bugfix, ingest

#999 Vertex AI training action
  default/methods/action/action_manual.py
  default/methods/action/action_new.py
  default/methods/action/action_run_list.py
  default/requirements.txt
  eventhandlers/action_runners/actions/VertexTrainDatasetAction.py
  eventhandlers/action_runners/actions/__init__.py
  eventhandlers/action_runners/base/ActionRunner.py
  eventhandlers/main.py
  eventhandlers/requirements.txt
  frontend/src/components/action/action_config_factory.vue
  frontend/src/components/action/action_configurations/VertexTrainDatasetAction/VertexTrainDatasetAction.vue
  frontend/src/components/action/action_configurations/action_config_mixin.js
  frontend/src/components/action/action_configurations/create_task/create_task_action_config.vue
  frontend/src/components/action/action_selector.vue
  frontend/src/components/action/actions_config_base/action_config_base.vue
  frontend/src/components/action/actions_config_base/action_config_wizard_base.vue
  frontend/src/components/action/actions_config_base/trigger_config.vue
  frontend/src/components/action/component_mapping.js
  frontend/src/components/action/workflow_builder.vue
  frontend/src/components/connection/connection_form.vue
  frontend/src/components/connection/connection_select.vue
  frontend/src/services/actionService.js
  frontend/src/store.js
  requirements.txt
  shared/annotation.py
  shared/connection/connection_strategy.py
  shared/connection/google_cloud_storage_connector.py
  shared/data_tools_core_gcp.py
  shared/database/action/action.py
  shared/database/action/action_run.py
  shared/database/connection/connection.py
  walrus/requirements.txt
Labels: actions

#1080 CORE-20 Support File Ingestion and Input Display
  default/methods/source_control/file/compound_file_new.py
  frontend/src/components/input/input_compound_dialog.vue
  frontend/src/components/input/input_view.vue
  frontend/src/services/inputService.ts
  frontend/tsconfig.json
  shared/communicate/email.py
  shared/connection/scale_ai_connector.py
  shared/data_tools_core_gcp.py
  shared/database/account/transaction.py
  shared/database/input.py
  shared/database/source_control/file.py
  shared/database/source_control/working_dir.py
  shared/database/tag/tag.py
  shared/database/video/sequence.py
  shared/database/video/video.py
  shared/ingest/packet.py
  shared/instance_tools.py
  shared/query_engine/sql_alchemy_query_elements/dataset_tag.py
  shared/query_engine/sqlalchemy_query_exectutor.py
  shared/utils/job_launch_utils.py
  walrus/methods/input/input_view.py
  walrus/methods/input/packet.py
  walrus/methods/input/process_media.py
  walrus/methods/input/upload.py
Labels: ready_to_merge, feature

#1088 Fix us shema request
  frontend/src/components/ui_schema/ui_schema.ts
  frontend/src/components/ui_schema/ui_schema_context_menu.vue
  frontend/src/helpers/interfaces/genaral/SchemaUI.ts
  frontend/src/services/schemaUIService.ts
  shared/database/task/job/job.py
Labels: bugfix

#1085 CORE-21 Support Move, Copy & Mirror of compound files
  default/tests/shared/utils/source_control/file/test_file_transfer_core.py
  shared/database/input.py
  shared/database/source_control/file.py
  shared/database/source_control/working_dir.py
  shared/tests/test_utils/data_mocking.py
  shared/utils/source_control/file/file_transfer_core.py
  walrus/methods/input/process_media.py
  walrus/methods/interservice/interservice_receive_api.py
Labels: ready_to_merge, feature

#1089 fix: add bucket to serialized assets
  shared/database/source_control/file.py
Labels: ready_to_merge

#1048 Storybook
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package.json
  frontend/src/components/report/charts/bar_chart.vue
  frontend/src/components/report/charts/bar_horizontal_chart.vue
  frontend/src/components/report/charts/bar_stacked_horizontal_chart.vue
  frontend/src/components/report/charts/line_chart.vue
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/tooltip_button.stories.js
  frontend/yarn.lock
Labels: docs, front-end, developer-experience

#1106 Fix: Uppercase Imports on GCP
  shared/connection/azure_connector.py
  shared/connection/google_cloud_storage_connector.py
  shared/connection/s3_connector.py
  shared/ingest/allowed_ingest_extensions.py
  walrus/methods/input/process_media.py
Labels: bugfix

#1092 CORE-22 Query Compound FIles on FIles Explorer
  .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml
  .github/workflows/publish_docker_images.yaml
  README.md
  default/methods/source_control/file/file_browser.py
  default/methods/source_control/file/file_get_child_files.py
  default/routes_init.py
  default/tests/methods/source_control/file/test_get_child_files.py
  default/tests/shared/utils/source_control/file/test_file_transfer_core.py
  frontend/cypress/e2e/diffgram/explore_dataset/explore_dataset_dataset_explorer.cy.js
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/commands/update_instance_command.ts
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/source_control/compound_file_preview.vue
  frontend/src/components/source_control/dataset_explorer.vue
  frontend/src/components/source_control/dataset_explorer_instance_filtering.ts
  frontend/src/components/source_control/file_preview.vue
  frontend/src/components/ui_schema/ui_schema.ts
  frontend/src/components/ui_schema/ui_schema_context_menu.vue
  frontend/src/components/video/video.vue
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/components/vue_canvas/v_bg.vue
  frontend/src/components/vue_canvas/video_drawable_canvas.vue
  frontend/src/helpers/interfaces/genaral/SchemaUI.ts
  frontend/src/services/fileServices.ts
  frontend/src/services/schemaUIService.ts
  frontend/src/types/files.ts
  frontend/src/types/models.ts
  frontend/src/types/mouse_position.ts
  frontend/src/utils/instance_utils.ts
  frontend/tests/unit/3d_annotation/sensor_fusion_editor.spec.js
  github_assets/3d_example.png
  github_assets/autoborder.gif
  github_assets/cloud_logos.png
  github_assets/diffgram-comparison-chart.PNG
  github_assets/diffgram_audio_interface.png
  github_assets/diffgram_geospatial_interface.png
  github_assets/diffgram_high_level.PNG
  github_assets/diffgram_solution.PNG
  github_assets/diffgram_text_interface.png
  github_assets/levels_of_integrations.PNG
  github_assets/roadmap.PNG
  github_assets/slack.png
  github_assets/stack_example.PNG
  github_assets/userscript_diagram.png
  github_assets/video_general.PNG
  github_assets/what_problem_diffgram_2021_sept.PNG
  shared/database/image.py
  shared/database/point_cloud/point_cloud.py
  shared/database/source_control/file.py
  shared/database/source_control/working_dir.py
  shared/database/task/job/job.py
  shared/database/video/video.py
  shared/query_engine/sqlalchemy_query_exectutor.py
  shared/url_generation.py
  walrus/methods/input/input_update.py
  walrus/methods/input/process_media.py
  walrus/methods/video/video.py
Labels: feature, pending_work

#1107 CORE-23 Export Support for Compound Files
  shared/export/export_generation.py
Labels: enhancement, ready_to_merge

#1108 fix: extra white space on task preview
  frontend/src/components/regular/file_preview_with_hover_expansion.vue
Labels: ready_to_merge, bugfix

#1109 CORE-24 Compound File Support on Tasks List
  default/methods/source_control/file/remove.py
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/regular/file_preview_with_hover_expansion.vue
  frontend/src/components/source_control/compound_file_preview.vue
  frontend/src/components/source_control/dataset_explorer.vue
  frontend/src/components/source_control/file_preview.vue
  frontend/src/components/source_control/file_preview_details_card.vue
  frontend/src/components/task/task/task_list.vue
  shared/utils/job_dir_sync_utils.py
Labels: enhancement, ready_to_merge

#1111 feat: CORE-27 New PR Template
  pull_request_template.md
Labels: ready_to_merge

#1116 fix: performance fixes for projects with large dirs list
  default/methods/project/view_project.py
  default/methods/source_control/working_dir/directory_update.py
  default/methods/source_control/working_dir/new_directory.py
  frontend/src/components/user/home/annotator_dashboard.vue
  frontend/src/components/user/home/dashboard.vue
  shared/alembic/versions_opencore/alembic_2022_10_13_06_51_61977555605b_new_indexes_for_dirs_and_events.py
  shared/database/project.py
  shared/database/source_control/working_dir.py
Labels: ready_to_merge, bugfix

#1123 fix: improve speed of task list fetching for files with connection ids
  default/methods/task/task/task_list.py
  frontend/src/components/task/task/task_list.vue
  shared/database/task/task.py
Labels: ready_to_merge, bugfix

#1129 fix: complete hotkey
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
Labels: ready_to_merge, bugfix

#1127 CORE-41 Add MinIO as default storage provider
  docker-compose.yaml
  install.py
  local_dispatcher/local_dispatch.py
  shared/data_tools_core_minio.py
Labels: ready_to_merge, feature
