Repository diffgram/diffgram, pull requests merged in 2022-06, with the labels that each got.

#909 E2e tests for the new interfaces
  frontend/cypress/e2e/diffgram/audio_interface/01_annotate_audio.cy.js
  frontend/cypress/e2e/diffgram/text_interface/01_annotate_text.cy.js
  frontend/cypress/fixtures/test-audio/audio_sample.mp3
  frontend/cypress/fixtures/test-text/text_sample.txt
  frontend/cypress/support/commands.js
  frontend/package.json
  frontend/src/components/audio_annotation/render_elements/waveform_selector.vue
  frontend/src/components/text_annotation/render_elements/text_context_menu.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/text_annotation/text_sidebar.vue
  frontend/src/components/text_annotation/text_toolbar.vue
  frontend/yarn.lock
Labels: testing

#911 Minor bug fixes
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/audio_annotation/render_elements/waveform_selector.vue
  shared/database/source_control/file.py
Labels: bugfix, front-end

#918 Fix global attributes on the Image interface
  default/methods/attribute/attribute_template_group.py
  frontend/src/components/annotation/annotation_core.vue
  shared/database/attribute/attribute_template_group.py
Labels: bugfix

#922 Fix Expiration TImes For S3 Client Defaults
  shared/data_tools_core_s3.py
  walrus/methods/input/process_media.py
Labels: bugfix, blob-storage-layer

#921 fix: improve dependencies of container in docker compose
  docker-compose.yaml
  eventhandlers/sudo
  install.py
Labels: bug, enhancement, devops, developer-experience

#917 Deep Checks Action
  default/main.py
  default/requirements.txt
  eventhandlers/action_runners/ActionRunner.py
  eventhandlers/action_runners/AzureTextAnalyticsSentiment.py
  eventhandlers/action_runners/DeepCheckImagePropertyOutliers.py
  eventhandlers/action_runners/ExportActionRunner.py
  eventhandlers/action_runners/GoogleVertexAIObjectDetectionPrediction.py
  eventhandlers/action_runners/SampleActionBoilerplate.py
  eventhandlers/action_runners/TaskTemplateActionRunner.py
  eventhandlers/action_runners/base/ActionCompleteCondition.py
  eventhandlers/action_runners/base/ActionCondition.py
  eventhandlers/action_runners/base/ActionRunner.py
  eventhandlers/action_runners/base/ActionTrigger.py
  eventhandlers/action_runners/base/__init__.py
  eventhandlers/action_runners/huggingface_zeroshot.py
  eventhandlers/action_runners/runners_mapping.py
  eventhandlers/main.py
  eventhandlers/requirements.txt
  frontend/src/components/action/action_config_factory.vue
  frontend/src/components/action/action_configurations/deepchecks/img_properties_outliers/img_properties_outliers_action_config.vue
  frontend/src/components/action/action_configurations/deepchecks/img_properties_outliers/img_properties_outliers_action_details.vue
  shared/database/action/action_run.py
  shared/database/source_control/working_dir.py
  shared/database_setup_supporting.py
  walrus/main.py
Labels: enhancement, workflow-experience

#930 Allow Fetch Schema on Public Projects
  default/methods/labels/label_schema_list.py
Labels: bugfix

#940 Fix Global Attributes Saving
  default/methods/attribute/attribute_template_list.py
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
Labels: ready_to_merge, bugfix

#945 Improvements to OIDC Abstraction Layer
  default/methods/auth/oidc/oidc_auth_callback.py
  default/methods/configs/oidc_is_set.py
  default/methods/startup/system_startup_checker.py
  default/methods/user/logout.py
  eventhandlers/startup/system_startup_checker.py
  shared/auth/KeycloakDiffgramClient.py
  shared/auth/OIDCProvider.py
  shared/helpers/permissions.py
  shared/permissions/KeycloakPolicyEnforcer.py
  shared/settings/settings.py
  walrus/methods/startup/system_startup_checker.py
Labels: enhancement, ready_to_merge
