Repository diffgram/diffgram, pull requests merged in 2022-09, with the labels that each got.

#1045 Improve explorer
  frontend/src/components/source_control/dataset_explorer.vue
Labels: bugfix, frontend-ui

#1043 feat: jobs list display improvements and multiple select
  default/methods/project/project_update.py
  default/methods/task/task_template/job_cancel.py
  default/methods/task/task_template/job_list.py
  frontend/cypress/e2e/diffgram/task/task/task_list_user_assign.cy.js
  frontend/cypress/e2e/diffgram/task_template/01_task_template_create.cy.js
  frontend/src/components/regular_concrete/job_status_select.vue
  frontend/src/components/task/job/job_list.vue
  frontend/src/components/task/job/job_list_card_display.vue
  frontend/src/components/user/member_select.vue
  shared/alembic/versions_opencore/alembic_2022_08_02_09_03_ed8dea09f743_add_file_stats_aggregate_table.py
Labels: ready_to_merge

#1044 feat: add files regeneration button
  default/methods/project/regen_file_stats.py
  default/routes_init.py
  frontend/src/components/project/settings.vue
Labels: ready_to_merge

#1051 Fixes Stats
  default/play_and_scripts/update_file_stats.py
  shared/database/source_control/file_stats.py
  shared/utils/attributes/attributes_values_parsing.py
Labels: ready_to_merge

#1053 fix: regen script and url regen on dataset explorer
  default/methods/project/regen_file_stats.py
  default/methods/source_control/file/file_browser.py
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/source_control/dataset_explorer.vue
  shared/alembic/versions_opencore/alembic_2022_09_12_18_15_56192ed7c6cd_new_file_indexes.py
  shared/database/source_control/file.py
  shared/database/source_control/file_stats.py
Labels: bugfix

#1062 Fix project creation request
  frontend/src/components/source_control/directory_new.vue
Labels: bugfix

#1059 Add Query Results as Tasks
  default/methods/source_control/file/file_browser.py
  default/methods/task/task_template/task_template_add_files.py
  default/routes_init.py
  eventhandlers/ConsumersCreator.py
  eventhandlers/JobsConsumer.py
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/regular/button_with_menu.vue
  frontend/src/components/regular/regular_error_handling.js
  frontend/src/components/source_control/dataset_explorer.vue
  frontend/src/components/source_control/dataset_explorer_toolbar.vue
  frontend/src/services/taskTemplateService.js
  frontend/yarn.lock
  shared/database/source_control/file.py
  shared/database/task/task.py
  shared/permissions/job_permissions.py
  shared/queueclient/QueueClient.py
  shared/utils/task/task_update_manager.py
Labels: ready_to_merge, feature

#1060 CORE-3 Azure Pass By Reference
  default/methods/configs/mailgun_is_set.py
  shared/connection/azure_connector.py
  shared/connection/s3_connector.py
  shared/data_tools_core_azure.py
  shared/regular/regular_input.py
  shared/settings/settings.py
  shared/url_generation.py
  walrus/methods/input/packet.py
Labels: ready_to_merge, feature

#1073 Replace Access Token With ID Token Cognito
  shared/helpers/permissions.py
Labels: feature

#1074 Fix saving on the text interface
  frontend/src/components/text_annotation/text_annotation_core.vue
Labels: bug, text-annotation

#1077 Compress Token During Token Refresh
  shared/helpers/permissions.py
Labels: ready_to_merge, feature
