Repository diffgram/diffgram, pull requests merged in 2022-03, with the labels that each got.

#679 Rescale Keypoints Snapping to Corners
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/utils/instance_utils.js
  frontend/tests/unit/annotation/annotation_core.spec.js
Labels: feature, front-end

#687 Upgrade dispatcher dependencies
  local_dispatcher/requirements.txt
Labels: ready_to_merge, bugfix

#695 Create Ellipse From Center
  default/methods/account/transact/transaction_list.py
  default/methods/action/action.py
  default/methods/source_control/file/file_browser.py
  default/methods/stats/stats.py
  default/methods/task/credential/credential_list.py
  default/methods/task/task_template/job_list.py
  default/methods/task/task_template/job_new_or_update.py
  default/methods/task/task_template/task_template_apply.py
  default/tests/shared/database/task/job/test_job.py
  frontend/src/components/vue_canvas/current_instance.vue
  shared/annotation.py
  shared/database/annotation/instance_template.py
  shared/database/attribute/attribute_template_group.py
  shared/database/event/event.py
  shared/database/source_control/file.py
  shared/database/task/job/job.py
  shared/utils/task/task_complete.py
Labels: ready_to_merge, bugfix

#692 Change panning to z key and reactivate turbo mode
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/vue_canvas/CanvasMouseTools.ts
  frontend/tests/unit/annotation/annotation_core.spec.js
Labels: ready_to_merge, bugfix

#691 Show/Hide Instance Templates on UI Schema
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/instance_type_multiple_select.vue
  frontend/src/services/instanceTemplateService.js
Labels: enhancement, ready_to_merge

#696 Fetch members and reviewers from job for changing assignees
  default/methods/task/task_template/task_template_member_list.py
  default/routes_init.py
  default/tests/methods/task/task_template/test_task_template_member_list.py
  frontend/src/components/dialogs/add_assignee.vue
  frontend/src/components/task/task/task_list.vue
  frontend/src/components/user/member_select.vue
  frontend/src/services/taskTemplateService.js
  shared/database/task/job/job.py
  shared/database/user.py
  shared/permissions/job_permissions.py
Labels: bugfix

#718 Add Support for Coloring Instance Templates
  frontend/src/assets/fill.ico
  frontend/src/assets/fill2.svg
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/context_menu/context_menu_instance_template.vue
  frontend/src/components/instance_templates/instance_template_creation_dialog.vue
  frontend/src/components/instance_templates/instance_template_creation_toolbar.vue
  frontend/src/components/regular/tooltip_button.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/components/vue_canvas/instances/InstanceContext.ts
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/components/vue_canvas/interactions/InstanceTemplateCreationInteractionGenerator.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseMove.ts
  frontend/src/utils/colorUtils.js
  frontend/src/utils/custom_icons.js
Labels: ready_to_merge, feature

#659 Implementation of the new command pattern
  docker-compose.yaml
  frontend/package.json
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/components/vue_canvas/instances/TextInstance.ts
  frontend/src/helpers/command/avalible_commands/create.ts
  frontend/src/helpers/command/avalible_commands/delete.ts
  frontend/src/helpers/command/avalible_commands/index.ts
  frontend/src/helpers/command/avalible_commands/update.ts
  frontend/src/helpers/command/avalible_commands/update_label.ts
  frontend/src/helpers/command/command.ts
  frontend/src/helpers/command/command_manager.ts
  frontend/src/helpers/history.ts
  frontend/src/helpers/instance_list.ts
  frontend/src/helpers/interfaces/Command.ts
  frontend/src/helpers/interfaces/History.ts
  frontend/src/helpers/interfaces/InstanceData.ts
  frontend/tests/unit/helpers/TestCalsses/TestCommand.ts
  frontend/tests/unit/helpers/TestCalsses/TestHistory.ts
  frontend/tests/unit/helpers/TestCalsses/TestInstances.ts
  frontend/tests/unit/helpers/command/command_manager.spec.js
  frontend/tests/unit/helpers/history.spec.js
  frontend/tests/unit/helpers/instance_list.spec.js
  frontend/yarn.lock
Labels: code-structuring, developer-experience

#726 RIght Click Focus Instance
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/context_menu/context_menu.vue
Labels: feature

#725 Add Guided Drawing Mode for Keypoints Instances
  default/methods/annotation/instance_template_update.py
  frontend/cypress/integration/diffgram/annotate_files/02_instance_template_edit_spec.js
  frontend/cypress/support/commands.js
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/instance_templates/guided_1_click_mode_selector.vue
  frontend/src/components/instance_templates/instance_template_creation_dialog.vue
  frontend/src/components/instance_templates/instance_template_creation_toolbar.vue
  frontend/src/components/instance_templates/node_order_picker.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/components/vue_canvas/instances/InstanceContext.ts
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/tsconfig.json
  frontend/yarn.lock
  shared/alembic/versions_opencore/alembic_2022_03_07_13_14_13dc81c0b35d_add_mode_column_to_instance_template.py
  shared/database/annotation/instance_template.py
Labels: feature

#731 fix: Fix billing issue for users with no accounts.
  default/methods/account/billing/billing_stripe_new.py
  default/methods/user/account/account_new.py
  frontend/src/components/account/billing/credit_card.vue
  frontend/src/components/account/billing/order_premium.vue
Labels: ready_to_merge, bugfix

#736 DAD-132 Adjust Rescale Control Points for Instance Templates
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Labels: ready_to_merge, feature

#741 Add Better Carrousel Navigation
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
  frontend/src/components/annotation/qa_carousel.vue
  frontend/src/components/video/video.vue
Labels: ready_to_merge, feature

#640 Text interface v-1.1
  frontend/package.json
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/text_annotation/text_hotkeys.vue
  frontend/src/components/text_annotation/text_sidebar.vue
  frontend/src/components/text_annotation/text_toolbar.vue
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/components/vue_canvas/instances/TextInstance.ts
  frontend/src/helpers/command/available_commands/create.ts
  frontend/src/helpers/command/available_commands/delete.ts
  frontend/src/helpers/command/available_commands/index.ts
  frontend/src/helpers/command/available_commands/update.ts
  frontend/src/helpers/command/available_commands/update_label.ts
  frontend/src/helpers/command/command.ts
  frontend/src/helpers/command/command_manager.ts
  frontend/src/helpers/history.ts
  frontend/src/helpers/instance_list.ts
  frontend/src/helpers/interfaces/Command.ts
  frontend/src/helpers/interfaces/History.ts
  frontend/src/helpers/interfaces/InstanceData.ts
  frontend/src/services/instanceList.js
  frontend/tests/unit/helpers/TestCalsses/TestCommand.ts
  frontend/tests/unit/helpers/TestCalsses/TestHistory.ts
  frontend/tests/unit/helpers/TestCalsses/TestInstances.ts
  frontend/tests/unit/helpers/command/command_manager.spec.js
  frontend/tests/unit/helpers/history.spec.js
  frontend/tests/unit/helpers/instance_list.spec.js
  frontend/tests/unit/text_annotation/text_annotation_core.spec.js
  frontend/yarn.lock
Labels: text-annotation

#753 Dad 163 add tree structure attribute type frontend view
  frontend/package.json
  frontend/src/components/annotation/qa_carousel.vue
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/attribute/attribute_group_wizard.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/text_annotation/text_hotkeys.vue
  frontend/src/components/text_annotation/text_sidebar.vue
  frontend/src/components/text_annotation/text_toolbar.vue
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/components/vue_canvas/instances/TextInstance.ts
  frontend/src/helpers/command/available_commands/create.ts
  frontend/src/helpers/command/available_commands/delete.ts
  frontend/src/helpers/command/available_commands/index.ts
  frontend/src/helpers/command/available_commands/update.ts
  frontend/src/helpers/command/available_commands/update_label.ts
  frontend/src/helpers/command/command.ts
  frontend/src/helpers/command/command_manager.ts
  frontend/src/helpers/history.ts
  frontend/src/helpers/instance_list.ts
  frontend/src/helpers/interfaces/Command.ts
  frontend/src/helpers/interfaces/History.ts
  frontend/src/helpers/interfaces/InstanceData.ts
  frontend/src/services/instanceList.js
  frontend/tests/unit/helpers/TestClasses/TestCommand.ts
  frontend/tests/unit/helpers/TestClasses/TestHistory.ts
  frontend/tests/unit/helpers/TestClasses/TestInstances.ts
  frontend/tests/unit/helpers/command/command_manager.spec.js
  frontend/tests/unit/helpers/history.spec.js
  frontend/tests/unit/helpers/instance_list.spec.js
  frontend/tests/unit/text_annotation/text_annotation_core.spec.js
  frontend/yarn.lock
  walrus/methods/connectors/labelbox_connector.py
Labels: frontend-ui, front-end

#759 Fix bug pointed by Pablo
  frontend/src/components/attribute/attribute_group_wizard.vue
Labels: bugfix

#766 Fix search clearing issue
  frontend/src/components/attribute/attribute_group.vue
Labels: bugfix

#770 Fix/start annotation error
  frontend/src/components/task/job/job_detail.vue
  frontend/src/components/user/home/annotator_dashboard.vue
Labels: bugfix

#769 Fix project menu popup
  frontend/src/components/main_menu/menu.vue
Labels: bugfix

#771 Add deploy/test by comment
  .github/workflows/diffgram_testing.yaml
  .github/workflows/e2e_tests.yaml
  .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml
  frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js
  walrus/methods/data_mocking/generate_data.py
Labels: feature, devops
