Repository diffgram/diffgram, pull requests merged in 2022-04, with the labels that each got.

#774 DAD-168 Populate default ordinals in case instance template does not have
  frontend/cypress/integration/diffgram/annotate_files/11_autoborder_spec.js
  frontend/src/components/annotation/annotation_core.vue
  local_dispatcher/local_dispatch.py
Labels: ready_to_merge, bugfix

#786 DAD-174 Add search on labels selector
  frontend/src/components/label/label_select_annotation.vue
Labels: enhancement, ready_to_merge

#785 Remove blipping when changing video frame
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/input/upload_wizard_sheet.vue
  frontend/src/components/vue_canvas/v_bg.vue
Labels: ready_to_merge, bugfix

#825 Fix User Assignment on Job Detail
  default/methods/task/task_template/job_new_or_update.py
  frontend/src/components/dialogs/add_assignee.vue
  frontend/src/components/task/task/task_list.vue
  shared/database/task/job/job.py
Labels: ready_to_merge, bugfix

#830 Fix Task List Fetching
  frontend/src/components/source_control/file_preview.vue
  frontend/src/components/task/task/task_list.vue
  frontend/src/components/vue_canvas/video_drawable_canvas.vue
Labels: bugfix

#831 Fix Global Attribute Display
  frontend/src/components/attribute/attribute_group_list.vue
Labels: bugfix

#818 Geo interface V1
  README.md
  default/methods/source_control/file/file_browser.py
  default/methods/task/task_template/job_new_or_update.py
  default/tests/methods/annotation/test_instance_template_list.py
  default/tests/methods/annotation/test_instance_template_new.py
  default/tests/shared/test_annotation.py
  frontend/package.json
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/labels_page.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/annotation/schema_card_selector.vue
  frontend/src/components/geo_annotation/geo_annotation_core.vue
  frontend/src/components/geo_annotation/geo_hotkeys.vue
  frontend/src/components/geo_annotation/geo_sidebar.vue
  frontend/src/components/geo_annotation/geo_toolbar.vue
  frontend/src/components/input/new_or_update_upload_screen.vue
  frontend/src/components/input/upload_wizard_sheet.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/vue_canvas/instances/GeoInstance.ts
  frontend/src/components/vue_canvas/instances/TextInstance.ts
  frontend/src/helpers/command/available_commands/index.ts
  frontend/src/helpers/command/available_commands/update_geo_coordinates.ts
  frontend/src/helpers/command/command.ts
  frontend/src/helpers/interfaces/InstanceData.ts
  frontend/tests/unit/annotation/annotation_core.spec.js
  frontend/tests/unit/annotation/schema_card_selector.spec.js
  frontend/tests/unit/annotation/toolbar.spec.js
  frontend/tests/unit/task/job/task_template_wizard_creation/__snapshots__/step_label_schema_selection_task_template.spec.js.snap
  frontend/tests/unit/task/job/task_template_wizard_creation/step_label_schema_selection_task_template.spec.js
  frontend/yarn.lock
  github_assets/diffgram_geospatial_interface.png
  shared/alembic/versions_opencore/alembic_2022_04_21_11_10_e7d84ad133ea_add_geospatial_tables_and_columns.py
  shared/annotation.py
  shared/database/annotation/instance.py
  shared/database/geospatial/__init__.py
  shared/database/geospatial/geo_asset.py
  shared/database/source_control/file.py
  shared/database/source_control/working_dir.py
  shared/settings/settings.py
  shared/tests/test_utils/data_mocking.py
  walrus/Dockerfile
  walrus/methods/geotiff/GeoTiffProcessor.py
  walrus/methods/geotiff/__init__.py
  walrus/methods/input/process_media.py
  walrus/requirements.txt
Labels: geo-annotation
