Repository diffgram/diffgram, pull requests merged in 2022-05, with the labels that each got.

#838 Fix Export Generation Limit Checks
  walrus/methods/export/export_web.py
Labels: bugfix

#845 AWS Signature Fix
  install.py
  shared/data_tools_core_s3.py
  shared/settings/settings.py
Labels: ready_to_merge

#843 Text interface v1.2
  frontend/src/components/text_annotation/render_elements/fast_label_menu.vue
  frontend/src/components/text_annotation/render_elements/relation_in_progress.vue
  frontend/src/components/text_annotation/render_elements/selection.vue
  frontend/src/components/text_annotation/render_elements/text_context_menu.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/text_annotation/text_hotkeys.vue
  frontend/src/components/text_annotation/text_sidebar.vue
  frontend/src/components/text_annotation/text_toolbar.vue
  frontend/src/components/text_annotation/text_utils/closest_token.ts
  frontend/src/components/text_annotation/text_utils/draw_rects.ts
  frontend/src/components/vue_canvas/instances/TextInstance.ts
  frontend/src/helpers/command/available_commands/delete.ts
  frontend/src/helpers/command/available_commands/index.ts
  frontend/src/helpers/command/available_commands/update_attribute.ts
  frontend/src/helpers/instance_list.ts
  frontend/src/helpers/interfaces/InstanceData.ts
  frontend/tests/unit/helpers/TestClasses/TestInstances.ts
  frontend/tests/unit/text_annotation/text_annotation_core.spec.js
  walrus/methods/text_data/text_tokenizer.py
  walrus/tests/methods/text_data/test_text_tokenizer.py
Labels: text-annotation

#856 fix: s3 export bug
  walrus/methods/connectors/s3_connector.py
Labels: bugfix, backend

#857 add minio support
  .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml
  docker-compose.yaml
  frontend/src/components/connection/connection_form.vue
  frontend/src/components/connection/connection_select.vue
  frontend/src/components/connectors/connector_import_renderer.vue
  frontend/src/components/export/connector_export_renderer.vue
  frontend/src/store.js
  install.py
  shared/alembic/versions_opencore/alembic_2022_05_10_06_42_58e15bf26b41_add_minio_config_private_host.py
  shared/connection/connection_operations.py
  shared/data_tools_core.py
  shared/data_tools_core_minio.py
  shared/data_tools_core_s3.py
  shared/database/connection/connection.py
  shared/settings/settings.py
  walrus/methods/connectors/connector_interface.py
  walrus/methods/connectors/connector_interface_utils.py
  walrus/methods/connectors/connectors.py
  walrus/methods/connectors/minio_connector.py
  walrus/methods/connectors/s3_connector.py
  walrus/methods/export/export_utils.py
Labels: enhancement

#829 Audio interface V1
  .github/workflows/diffgram_testing.yaml
  .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml
  README.md
  default/methods/source_control/file/file_browser.py
  default/tests/shared/database/audio/__init__.py
  default/tests/shared/database/audio/test_audio_file.py
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/annotation/media_core.vue
  frontend/src/components/audio_annotation/audio_annotation_core.vue
  frontend/src/components/audio_annotation/audio_hotkeys.vue
  frontend/src/components/audio_annotation/audio_sidebar.vue
  frontend/src/components/audio_annotation/audio_toolbar.vue
  frontend/src/components/audio_annotation/render_elements/waveform_selector.vue
  frontend/src/components/input/input_view.vue
  frontend/src/components/input/new_or_update_upload_screen.vue
  frontend/src/components/vue_canvas/instances/AudioInstance.ts
  frontend/src/helpers/command/available_commands/index.ts
  frontend/src/helpers/command/available_commands/update_audio_coordinates.ts
  frontend/src/helpers/command/command.ts
  frontend/yarn.lock
  github_assets/diffgram_audio_interface.png
  shared/alembic/versions_opencore/alembic_2022_03_03_11_21_ee1f8ffb8c4d_add_audio_file_table.py
  shared/annotation.py
  shared/database/annotation/instance.py
  shared/database/audio/__init__.py
  shared/database/audio/audio_file.py
  shared/database/source_control/file.py
  shared/tests/test_utils/data_mocking.py
  walrus/methods/input/process_media.py
  walrus/tests/methods/input/test_process_media.py
Labels: audio-annotation

#879 DAD-276 Fix Label Dict Endpoint to Include Schema Concept
  default/methods/annotation/labels/view.py
  shared/database/project.py
Labels: ready_to_merge, bugfix
