Repository diffgram/diffgram, pull requests merged in 2022-02, with the labels that each got.

#289 Default file level options - WIP
  .github/workflows/diffgram_testing.yaml
  default/methods/annotation/labels/labels.py
  default/methods/attribute/attribute_template_group_update.py
  default/methods/attribute/attribute_template_list.py
  frontend/cypress/integration/diffgram/annotate_files/04_annotate_files_attributes_spec.js
  frontend/src/components/account/billing/order_premium.vue
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/instance_detail_list_view.vue
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/attribute/attribute_group_list.vue
  frontend/src/components/attribute/attribute_group_wizard.vue
  frontend/src/components/attribute/attribute_kind_icons.vue
  frontend/src/components/attribute/global_attributes_list.vue
  frontend/src/components/input/diffgram_export_validator.vue
  frontend/src/components/instance_templates/instance_template_creation_dialog.vue
  frontend/src/components/label/label_select_annotation.vue
  frontend/src/components/regular/tooltip_icon.vue
  frontend/src/components/task/job/job_detail.vue
  shared/alembic/versions_opencore/alembic_2022_01_24_09_13_8736666d667d_add_tokenizer_signed_url_columns.py
  shared/alembic/versions_opencore/alembic_2022_01_26_01_01_e1739d7f895f_add_global_attributes.py
  shared/annotation.py
  shared/database/annotation/instance.py
  shared/database/attribute/attribute_template_group.py
  shared/database/project.py
  shared/database/source_control/file.py
  shared/database/task/task.py
  shared/database/text_file.py
  walrus/methods/export/export_generation.py
  walrus/tests/methods/text_data/test_text_tokenizer.py
Labels: enhancement, ready_to_merge

#552 Fix Video: animation was not stopping even though video ended
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/video/video.vue
Labels: ready_to_merge, bugfix

#576 DAD-28 Time Tracking
  default/methods/report/custom_reports/AnnotatorPerformanceReport.py
  default/methods/report/custom_reports/TimeSpentReport.py
  default/methods/report/custom_reports/__init__.py
  default/methods/report/report_runner.py
  default/methods/report/report_view_api.py
  default/methods/task/stats/fast_stats.py
  default/methods/task/task/task_annotator_request.py
  default/methods/task/task/task_by_id.py
  default/methods/task/task_time_tracking/__init__.py
  default/methods/task/task_time_tracking/task_track_time.py
  default/methods/ui_schema/ui_schema.py
  default/routes_init.py
  default/tests/methods/task/task_time_tracking/__init__.py
  default/tests/methods/task/task_time_tracking/test_task_track_time.py
  default/tests/shared/database/task/test_task_time_tracking.py
  frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js
  frontend/cypress/integration/diffgram/task_template/01_task_template_create_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/3d_annotation/sensor_fusion_editor.vue
  frontend/src/components/3d_annotation/toolbar_sensor_fusion.vue
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/dialogs/add_assignee.vue
  frontend/src/components/label/label_select_only.vue
  frontend/src/components/main_menu/menu_project.vue
  frontend/src/components/main_menu/menu_tasks.vue
  frontend/src/components/report/annotator_performance.vue
  frontend/src/components/report/report.vue
  frontend/src/components/report/report_list.vue
  frontend/src/components/report/stats_task.vue
  frontend/src/components/report/task_time_spent.vue
  frontend/src/components/stats/stats_panel.vue
  frontend/src/components/task/job/job_detail.vue
  frontend/src/components/task/job/job_select.vue
  frontend/src/components/task/time_track/time_tracker.vue
  frontend/src/components/ui_schema/ui_schema_context_menu.vue
  frontend/src/components/ui_schema/ui_schema_task_mock.js
  frontend/src/components/user/member_select.vue
  frontend/src/components/video/video.vue
  frontend/src/services/reportServices.js
  frontend/src/services/tasksServices.js
  frontend/src/store.js
  frontend/tests/unit/stats/stats_panel.spec.js
  shared/alembic/versions_opencore/alembic_2021_05_12_10_11_990839b415fc_add_prelabeled_data_to_input_batch.py
  shared/alembic/versions_opencore/alembic_2022_02_03_13_36_ddcdf79c4cbc_rename_base_class_string_column_reports_.py
  shared/alembic/versions_opencore/alembic_2022_02_04_10_56_a9023fc32298_add_time_tracking_table.py
  shared/alembic/versions_opencore/alembic_2022_02_09_10_26_4b2b0450b93b_add_time_tracking_to_ui_schema.py
  shared/database/report/report_template.py
  shared/database/task/task.py
  shared/database/task/task_time_tracking.py
  shared/database/ui_schema/ui_schema.py
  shared/event_emitter/__init__.py
  shared/event_emitter/event_emitter.py
  shared/permissions/project_permissions.py
  shared/permissions/task_permissions.py
Labels: feature, pending_work, front-end, backend

#589 DAD-46 only hover 1 instance when multiple instances overlayed
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/vue_canvas/instances/InstanceContext.ts
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Labels: ready_to_merge, bugfix

#588 DAD-43 fix: misplaced rotate point after drawing
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/toolbar.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Labels: ready_to_merge, bugfix

#603 Allow Test Workflows on Base PRs
  .github/workflows/diffgram_testing.yaml
Labels: ready_to_merge

#587 DAD-42 Do not allow select instances while drawing
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Labels: ready_to_merge, bugfix

#604 DAD-48 Occlude Childs
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/context_menu/context_menu.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/components/vue_canvas/interactions/Interaction.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseDown.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseUp.ts
Labels: ready_to_merge, feature

#607 Resize Existing Keypoints instances
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/user/account/user_data_platform_new.vue
  frontend/src/components/vue_canvas/instance_list.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseMove.ts
Labels: ready_to_merge, feature

#611 fix: change panning to shift key
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/hotkeys.vue
Labels: ready_to_merge, feature

#609 fix: creating template on UI
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/vue_canvas/current_instance_template.vue
  frontend/src/utils/instance_utils.js
Labels: ready_to_merge, bugfix

#610 Instance Template Creation Fixes
  .github/workflows/diffgram_testing.yaml
  frontend/src/components/annotation/node_name_editor_keypoint_instance.vue
  frontend/src/components/instance_templates/instance_template_creation_dialog.vue
  frontend/src/components/vue_canvas/drawable_canvas.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  frontend/src/components/vue_canvas/interactions/AnnotationCoreInteractionGenerator.ts
  frontend/src/components/vue_canvas/interactions/InstanceTemplateCreationInteractionGenerator.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseMove.ts
  frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseUp.ts
Labels: bugfix, pending_work

#629 Add 401 Status codes to backend for not logged in users
  frontend/src/components/account/account/account_info.vue
  frontend/src/components/account/transaction/transaction_list.vue
  frontend/src/components/action/action_event_list.vue
  frontend/src/components/action/action_existing_list.vue
  frontend/src/components/action/action_flow_event_list.vue
  frontend/src/components/annotation/instance_history_sidepanel.vue
  frontend/src/components/annotation/labels_new.vue
  frontend/src/components/project/tags.vue
  frontend/src/components/task/job/job_detail_trainer.vue
  frontend/src/components/task/job/job_new.vue
  frontend/src/services/instanceList.js
  frontend/src/services/jobStatsServices.js
  frontend/src/services/mockServices.js
  frontend/src/services/projectServices.js
  frontend/tests/unit/user/login.spec.js
  shared/database/auth/api.py
  shared/permissions/account_permissions.py
  shared/permissions/api_permissions.py
  shared/permissions/features.py
  shared/permissions/general.py
  shared/permissions/job_permissions.py
  shared/permissions/project_permissions.py
  shared/permissions/super_admin_only.py
  shared/permissions/task_permissions.py
  shared/permissions/user_permissions.py
Labels: ready_to_merge, bugfix, backlog

#642 fix: add unit testing DB url
  .github/workflows/diffgram_testing.yaml
  default/tests/conftest.py
  shared/settings/settings.py
  walrus/tests/conftest.py
Labels: enhancement, backend

#636 DAD-81 Exam Now Duplicate Files
  frontend/cypress/fixtures/users.json
  frontend/cypress/integration/diffgram/task_template/02_task_submit_to_review_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/exam/exam_new.vue
  frontend/src/components/regular/file_preview_with_hover_expansion.vue
  frontend/src/components/task/job/job_list_card_display.vue
  frontend/src/services/customInstance/index.js
  shared/utils/task/task_new.py
  walrus/methods/task/task_template/task_template_launch_handler.py
Labels: ready_to_merge, feature

#658 Improve Invite Experience & Bug Fixes
  default/methods/configs/is_open_source.py
  default/methods/share/share.py
  default/methods/startup/system_startup_checker.py
  default/methods/user/account/account_new.py
  default/methods/user/account/auth_code.py
  default/routes_init.py
  frontend/src/components/exam/exam_child_list.vue
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/main_menu/menu_marketing.vue
  frontend/src/components/marketing/home_unbounce.vue
  frontend/src/components/regular/ahref_seo_optimal.vue
  frontend/src/components/user/account/user_data_platform_new.vue
  frontend/src/components/user/builder/builder_signup.vue
  frontend/src/components/user/home/annotator_dashboard.vue
  frontend/src/components/user/home/dashboard.vue
  frontend/src/components/user/login.vue
  frontend/src/services/configService.js
  frontend/src/services/projectServices.js
  shared/system_startup/system_startup_base.py
  walrus/methods/startup/system_startup_checker.py
Labels: bugfix

#672 Fix instance being dragged without clicking bug
  frontend/cypress/integration/diffgram/export_annotated_data/export_spec.js
  frontend/cypress/integration/diffgram/task_template/02_task_submit_to_review_spec.js
  frontend/cypress/support/commands.js
  frontend/src/components/export/export_home.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
  walrus/methods/data_mocking/generate_data.py
Labels: bugfix, front-end

#674 fix: target reticle display on template creation
  frontend/src/components/instance_templates/instance_template_creation_dialog.vue
  frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Labels: bugfix
