Repository diffgram/diffgram, pull requests merged in 2022-12, with the labels that each got.

#1227 Instance Store
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/helpers/InstanceStore.ts
Labels: refactor

#1235 feat: Polygon Instance Refactor
  frontend/package.json
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/commands/create_instance_command.ts
  frontend/src/components/context_menu/context_menu.vue
  frontend/src/components/report/report.vue
  frontend/src/components/source_control/file_preview.vue
  frontend/src/components/vue_canvas/CanvasMouseTools.ts
  frontend/src/components/vue_canvas/advanced_tools/PolygonAutoBorderTool.ts
  frontend/src/components/vue_canvas/advanced_tools/PolygonMergeTool.ts
  frontend/src/components/vue_canvas/coordinators/Coordinator.ts
  frontend/src/components/vue_canvas/coordinators/ImageAnnotationCoordinatorRouter.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/BoxInstanceCoordinator.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/ImageAnnotationCoordinator.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/PolygonInstanceCoordinator.ts
  frontend/src/components/vue_canvas/current_instance.vue
  frontend/src/components/vue_canvas/instance_list.vue
  frontend/src/components/vue_canvas/instances/BoxInstance.ts
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/components/vue_canvas/instances/InstanceImage2D.ts
  frontend/src/components/vue_canvas/instances/PolygonInstance.ts
  frontend/src/components/vue_canvas/video_drawable_canvas.vue
  frontend/src/types/InteractionEvent.ts
  frontend/src/types/image_label_settings.ts
  frontend/src/types/mouse_position.ts
  frontend/src/utils/instance_utils.ts
  frontend/tests/unit/annotation/annotation_core.spec.js
  frontend/yarn.lock
Labels: ready_to_merge, refactor, code-readability

#1236 Instance store video context
  frontend/src/components/annotation/annotation_core.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/helpers/InstanceStore.ts
Labels: refactor, composable-ui

#1247 Fix Typescript and Tests
  frontend/cypress/e2e/diffgram/3d_interface/01_show_3d_point_cloud.cy.js
  frontend/src/App.vue
  frontend/src/components/main_menu/menu.vue
  frontend/src/components/vue_canvas/coordinators/ImageAnnotationCoordinatorRouter.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/BoxInstanceCoordinator.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/ImageAnnotationCoordinator.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/KeypointInstanceCoordinator.ts
  frontend/src/components/vue_canvas/coordinators/coordinator_types/PolygonInstanceCoordinator.ts
  frontend/src/components/vue_canvas/instances/BoxInstance.ts
  frontend/src/router/router.js
  frontend/src/types/InteractionEvent.ts
  frontend/tests/unit/annotation/annotation_core.spec.js
Labels: refactor, testing

#1255 Geo annotation improvements
  frontend/src/components/geo_annotation/geo_annotation_core.vue
Labels: bugfix

#1258 Geo xyz tiles
  eventhandlers/action_runners/actions/ExportActionRunner.py
  eventhandlers/action_runners/base/ActionRunner.py
  frontend/package.json
  frontend/src/components/action/action_configurations/export/export_config_details.vue
  frontend/src/components/geo_annotation/geo_annotation_core.vue
  frontend/src/components/geo_annotation/geo_tile.vue
  frontend/src/components/geo_annotation/geo_toolbar.vue
  frontend/src/components/regular/file_preview_with_hover_expansion.vue
  frontend/yarn.lock
  shared/data_tools_core.py
  shared/data_tools_core_s3.py
  shared/url_generation.py
Labels: geo-annotation

#1269 Fix insights panel
  frontend/src/components/report/annotator_performance.vue
  frontend/src/components/report/approval_reject_ratio.vue
  frontend/src/components/report/task_time_spent.vue
  frontend/src/components/report/tasks_count_per_user.vue
  frontend/src/components/report/tasks_percentage_user.vue
  frontend/src/components/stats/stats_panel.vue
  frontend/tests/unit/stats/stats_panel.spec.js
  shared/database/task/task.py
Labels: bugfix, reporting

#1268 Re-project geotiff to EPSG:3857 on upload
  walrus/methods/geotiff/GeoTiffProcessor.py
Labels: geo-annotation
