Repository diffgram/diffgram, pull requests merged in 2023-02, with the labels that each got.

#1308 Add Global Attributes for Root Compound Files
  default/methods/annotation/annotation.py
  default/methods/annotation/labels/labels.py
  default/methods/attribute/attribute_template_group_update.py
  default/methods/source_control/file/compound_file_new.py
  default/methods/source_control/file/file_browser.py
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/geo_annotation/geo_annotation_core.vue
  frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue
  frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue
  frontend/src/components/annotation/image_and_video_annotation/sidebar_image_annotation.vue
  frontend/src/components/annotation/sidebar_factory.vue
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/attribute/attribute_group_wizard.vue
  frontend/src/components/attribute/global_attributes_list.vue
  frontend/src/components/vue_canvas/instances/GlobalInstance.ts
  frontend/src/components/vue_canvas/instances/Instance.ts
  frontend/src/helpers/command/command.ts
  frontend/src/helpers/instance_list.ts
  frontend/src/types/AnnotationUIContext.ts
  frontend/src/types/attributes/AttributeTemplateGroup.ts
  shared/annotation.py
  shared/database/attribute/attribute_template_group.py
  shared/database/project.py
  shared/database/source_control/file.py
  shared/export/export_generation.py
Labels: enhancement, composable-ui

#1307 Fix free text attribute on the text interface
  frontend/src/components/annotation/text_annotation/text_annotation_core.vue
Labels: bugfix

#1310 CORE-61 Add Grid Support For Compound Files
  frontend/cypress/e2e/diffgram/annotate_files/09_data_integrity.cy.js
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue
  frontend/src/components/annotation/panel_manager.vue
  frontend/src/components/annotation/panel_manager_toolbar.vue
  frontend/src/components/annotation/panel_manager_width_height_controls.vue
  frontend/src/components/annotation/panel_metadata.vue
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/attribute/attribute_group_list.vue
  frontend/src/services/attributesService.js
  frontend/src/types/AnnotationUIContext.ts
  frontend/src/types/attributes/PanelsSettings.ts
  frontend/src/types/mouse_position.ts
  frontend/src/utils/instance_utils.ts
  walrus/methods/input/packet.py
Labels: feature

#1311 feat: add ordinal management to compound files
  .github/workflows/update_readme.yaml
  default/docs/file_update_metadata.yml
  default/methods/source_control/file/file_update_metadata.py
  frontend/package.json
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/panel_metadata.vue
  frontend/yarn.lock
  shared/alembic/versions_opencore/alembic_2023_02_03_15_55_0a4fd483f722_add_ordinal_to_files.py
  shared/database/input.py
  shared/database/source_control/file.py
  shared/database/video/video.py
  walrus/methods/geotiff/GeoTiffProcessor.py
  walrus/methods/input/packet.py
  walrus/methods/input/process_media.py
  walrus/methods/sensor_fusion/sensor_fusion_file_processor.py
  walrus/methods/video/video.py
Labels: enhancement

#1312 feat: flag for preventing all users except super admins to create projects
  .github/workflows/e2e_tests.yaml
  default/methods/project/project_new.py
  shared/settings/settings.py
Labels: enhancement, admin experience, config

#1313 Fix: Video Play Pause Layout & Sequence Container fitting
  .github/workflows/e2e_tests.yaml
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/video/sequence_list.vue
  frontend/src/components/video/video.vue
Labels: video-annotation, design

#1322 Add ordinal prop to from_local route
  walrus/methods/input/upload.py
Labels: bugfix

#1326 feat: add read only attribute
  default/docs/swagger_spec.json
  default/main.py
  default/methods/attribute/attribute_template_group_update.py
  default/methods/source_control/file/file_update_metadata.py
  frontend/src/components/attribute/attribute_group.vue
  frontend/src/components/attribute/attribute_group_list.vue
  frontend/src/components/attribute/attribute_group_wizard.vue
  frontend/src/components/attribute/attribute_select.vue
  frontend/src/services/attributesService.ts
  frontend/src/types/attributes/AttributeTemplateGroup.ts
  shared/alembic/versions_opencore/alembic_2023_02_23_08_38_7c18149a20c8_add_read_only_flag_to_attributes.py
  shared/database/attribute/attribute_template_group.py
Labels: feature, query-explorer, attributes

#1309 Text compound file
  default/methods/source_control/file/compound_file_new.py
  default/methods/source_control/file/file_browser.py
  frontend/src/components/annotation/annotation_area_factory.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/hotkeys/HotKeysManager.ts
  frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue
  frontend/src/components/annotation/image_and_video_annotation/media_core.vue
  frontend/src/components/annotation/panel_manager.vue
  frontend/src/components/annotation/panel_manager_toolbar.vue
  frontend/src/components/annotation/sidebar_factory.vue
  frontend/src/components/annotation/text_annotation/render_elements/conversational_meta.vue
  frontend/src/components/annotation/text_annotation/render_elements/fast_label_menu.vue
  frontend/src/components/annotation/text_annotation/render_elements/selection.vue
  frontend/src/components/annotation/text_annotation/render_elements/text_context_menu.vue
  frontend/src/components/annotation/text_annotation/text_annotation_core.vue
  frontend/src/components/annotation/text_annotation/text_sidebar.vue
  frontend/src/components/annotation/text_annotation/text_toolbar.vue
  frontend/src/components/annotation/toolbar_factory.vue
  frontend/src/components/regular/file_preview_with_hover_expansion.vue
  frontend/src/components/source_control/file_preview.vue
  frontend/src/services/instanceList.js
  frontend/src/types/AnnotationUIContext.ts
  frontend/src/types/attributes/PanelsSettings.ts
  frontend/tests/unit/text_annotation/render_elements/fast_label_menu.spec.js
  frontend/tests/unit/text_annotation/render_elements/selection.spec.js
  frontend/tests/unit/text_annotation/render_elements/text_context_menu.spec.js
  frontend/tests/unit/text_annotation/text_annotation_core.spec.js
  frontend/tests/unit/text_annotation/text_sidebar.spec.js
  shared/annotation.py
Labels: text-annotation
