Repository diffgram/diffgram, pull requests merged in 2023-01, with the labels that each got.

#1270 New geo interface functionality
  frontend/src/components/attribute/attribute_group_list.vue
  frontend/src/components/attribute/global_attributes_list.vue
  frontend/src/components/geo_annotation/geo_annotation_core.vue
  frontend/src/components/geo_annotation/geo_sidebar.vue
  frontend/src/components/geo_annotation/geo_tile.vue
  frontend/src/components/geo_annotation/geo_toolbar.vue
  frontend/src/components/text_annotation/text_annotation_core.vue
  frontend/src/components/vue_canvas/instances/GeoInstance.ts
  frontend/src/services/attributesService.js
  walrus/methods/geotiff/GeoTiffProcessor.py
Labels: geo-annotation

#1275 Fix report label names
  default/methods/report/report_runner.py
  frontend/src/components/report/CSVReportFormatter.ts
  frontend/src/components/report/report.vue
Labels: reporting

#1279 Create component to return correct interafce
  frontend/src/components/annotation/annotation_area_factory.vue
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/router/router.js
Labels: refactor

#1281 Create toolbar compoennt
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue
Labels: refactor

#1293 Add relations to the text export
  shared/export/export_generation.py
Labels: bugfix

#1302 Small fixes for the Geo Interface
  frontend/src/components/annotation/annotation_ui_factory.vue
  frontend/src/components/annotation/geo_annotation/geo_annotation_core.vue
  frontend/src/components/annotation/panel_manager.vue
Labels: bugfix, geo-annotation

#1303 Fix reading keydown of undefined console error
  frontend/src/components/annotation/annotation_ui_factory.vue
Labels: bugfix

#1304 Allow drawing text instances with different labels
  frontend/src/components/annotation/text_annotation/text_annotation_core.vue
Labels: bugfix
